// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// GetRepo provides a mock function with given fields: number
func (_m *UserRepository) GetRepo(number int) int {
	ret := _m.Called(number)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(number)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
